# Generated by Django 5.0 on 2024-01-08 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('number_attempt', models.IntegerField(default=0)),
                ('number_attempt_otp', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('date_naissance', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
